name: Scoring API

on:
  push:
    branches:
      - main
    paths:
      - "./hw3-oop-scoring"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Test with unittest
        working-directory: ./hw3-oop-scoring
        run: python3 -m unittest -v tests.py
