name: OTUServer

on:
  push:
    branches:
      - master
    paths:
      - "hw4-otuserver/**"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install ap tool
        run: |
          sudo apt-get update
          sudo apt-get install apache2-utils
      - name: Clone testing repo
        working-directory: ./hw4-otuserver
        run: git clone https://github.com/s-stupnikov/http-test-suite www
      - name: Replace 80 port with 8080 for testing
        working-directory: ./hw4-otuserver/www
        run: sed -i 's/80/8080/g' httptest.py
      - name: Run http server
        working-directory: ./hw4-otuserver
        run: python3 httpd.py -p 8080 -w 2 -r www &
      - name: Test http server
        working-directory: ./hw4-otuserver/www
        run: python3 httptest.py
      - name: Load testing results with Apache Benchmark
        run: ab -n 50000 -c 100 -r http://127.0.0.1:8080/httptest/dir2/page.html
