name: Scoring API

on:
  push:
    branches:
      - master
    paths:
      - "hw6-uwsgi-weather/ip2w/**"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Test with unittest
        working-directory: ./hw6-uwsgi-weather/ip2w
        run: python3 -m unittest -v
